Repository Shift3/boilerplate-client-angular, pull requests merged in 2022-01, with the labels that each got.

#370 chore(package.json): version bump to 1.0.1
  package.json
Labels: documentation

#368 Refactor terraform by start implementing terraform-modules
  README.md
  terraform/cloudfront/main.tf
  terraform/cloudfront/variables.tf
  terraform/environment/example.tfvars
  terraform/main.tf
  terraform/main/main.tf
  terraform/main/staging/.terraform.lock.hcl
  terraform/main/staging/main.tf
  terraform/main/staging/variables.tf
  terraform/main/variables.tf
  terraform/variables.tf
Labels: enhancement, feature, refactor

#374 Fix yarn lock and linting
  yarn.lock
Labels: bug

#379 Update CODEOWNERS to current team
  .github/CODEOWNERS
Labels: docs
